"""queue dna agent schema

Revision ID: ab2da16f5d05
Revises: 26905d2b3586
Create Date: 2026-07-16 00:37:12.945753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab2da16f5d05'
down_revision: Union[str, Sequence[str], None] = '26905d2b3586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_candidate_tracks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('source_platform', sa.String(length=20), nullable=False),
    sa.Column('track_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('valence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('energy', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('normalized_track_key', sa.String(length=511), nullable=False),
    sa.Column('normalized_artist_key', sa.String(length=511), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('playlist_overlap_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('shared_artist_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence IN ('high', 'low')", name='session_candidate_tracks_confidence_check'),
    sa.CheckConstraint("source_platform IN ('spotify', 'youtube')", name='session_candidate_tracks_platform_check'),
    sa.ForeignKeyConstraint(['participant_id'], ['session_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'participant_id', 'track_id', name='uq_candidate_participant_track')
    )
    op.add_column('queue_tracks', sa.Column('confidence', sa.String(length=10), server_default='high', nullable=False))
    op.add_column('queue_tracks', sa.Column('playlist_overlap_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('queue_tracks', sa.Column('shared_artist_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('queue_tracks', sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False))

    # --- Manually adjusted (autogenerate can't know about existing rows) ---
    # host_platform / selected_platform are added nullable, backfilled from
    # the corresponding user's (legacy, single-connection) `platform` column
    # — falling back to 'spotify' only for the rare legacy row whose user
    # never connected anything — then tightened to NOT NULL. Straight
    # NOT NULL with no default would fail outright against the 12 existing
    # sessions / participants already in this DB.
    op.add_column('session_participants', sa.Column('selected_platform', sa.String(length=20), nullable=True))
    op.execute("""
        UPDATE session_participants AS sp
        SET selected_platform = COALESCE(u.platform, 'spotify')
        FROM users AS u
        WHERE u.id = sp.user_id
    """)
    op.alter_column('session_participants', 'selected_platform', nullable=False)

    op.add_column('sessions', sa.Column('host_platform', sa.String(length=20), nullable=True))
    op.execute("""
        UPDATE sessions AS s
        SET host_platform = COALESCE(u.platform, 'spotify')
        FROM users AS u
        WHERE u.id = s.host_user_id
    """)
    op.alter_column('sessions', 'host_platform', nullable=False)

    op.add_column('sessions', sa.Column('session_dna', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('sessions', sa.Column('queue_build_status', sa.String(length=20), server_default='empty', nullable=False))
    op.add_column('sessions', sa.Column('effective_threshold', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('sessions', sa.Column('target_duration_minutes', sa.Integer(), nullable=True))
    op.alter_column('users', 'platform',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'platform',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('sessions', 'target_duration_minutes')
    op.drop_column('sessions', 'effective_threshold')
    op.drop_column('sessions', 'queue_build_status')
    op.drop_column('sessions', 'session_dna')
    op.drop_column('sessions', 'host_platform')
    op.drop_column('session_participants', 'selected_platform')
    op.drop_column('queue_tracks', 'is_current')
    op.drop_column('queue_tracks', 'shared_artist_count')
    op.drop_column('queue_tracks', 'playlist_overlap_count')
    op.drop_column('queue_tracks', 'confidence')
    op.drop_table('session_candidate_tracks')
    # ### end Alembic commands ###
